monitoring:
  sampling_interval: 1.0
  window_size: 3600

prediction:
  sequence_length: 60
  prediction_horizon: 10
  feature_dim: 3

services:
  auth-service:
    chains:
      - user-registration
      - order-processing
    min_cpu: 0.1
    max_cpu: 4.0
    min_memory: 128
    max_memory: 8192

  payment-service:
    chains:
      - order-processing
      - subscription-management
    min_cpu: 0.1
    max_cpu: 4.0
    min_memory: 128
    max_memory: 8192

slos:
  user-registration: 0.2
  order-processing: 0.5
  subscription-management: 0.3